### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/entrevista-tecno-power#1]
[REPORTE_DE_ENTREVISTA.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-tecno-power/files/7158959/REPORTE_DE_ENTREVISTA.pdf)

link del audio: https://drive.google.com/file/d/1JD5El2nt6grfRTpiA-WiH3vtu-E03uFm/view?usp=sharing

**Comment by Arnold-Js** [comment]
caliofico: Arnol Jesus Cruz Ortiz
calificacion.  20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
